@startuml

' Визначення акторів
actor "Користувач" as User
actor "Адміністратор" as Admin

' Визначення Use Cases
(User) --> (Відкрити Електронну Таблицю)
(User) --> (Редагувати Клітинку)
(User) --> (Додати Рядок)
(User) --> (Додати Стовпець)
(User) --> (Використовувати Функцію)
(User) --> (Перемкнути Режим Відображення)
(User) --> (Зберегти Таблицю)
(User) --> (Переглянути Помилки)
(User) --> (Експорт Таблиці)

(Admin) --> (Керувати Користувачами)
(Admin) --> (Налаштування Системи)
(Admin) --> (Переглянути Логи)

' Визначення взаємозв'язків між Use Cases
(Редагувати Клітинку) --> (Використовувати Функцію) : include
(Зберегти Таблицю) --> (Відкрити Електронну Таблицю) : include
(Зберегти Таблицю) --> (Редагувати Клітинку) : include
(Зберегти Таблицю) --> (Додати Рядок) : include
(Зберегти Таблицю) --> (Додати Стовпець) : include
(Використовувати Функцію) --> (Перемкнути Режим Відображення) : extend
(Переглянути Помилки) --> (Перемкнути Режим Відображення) : extend
(Експорт Таблиці) --> (Зберегти Таблицю) : include

@enduml
